### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by aldenchen** [UBC-MDS/DSCI-522_Titanic-Survival-Prediction#31]
- Just added a skeleton of the report. Right now, it's basically just loading the pictures.
- Note, I knitted it to pdf. If I knit to a '.md' file, the images look blurry, but they look fine in the pdf.

**Comment by aldenchen** [comment]
Also, knitting to `pdf_document` is pretty slow. It's faster to knit to a `github_document` when you are editing the report and want to see what it looks like. Just remember to knit a pdf at the end and push the pdf so the images look ok.

**Comment by aldenchen** [comment]
Just merged a pull request to add figure labels to the report.

**Comment by Birinder1469** [comment]
Looks ok.
